AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 60
    Handler: app.handler
    Runtime: nodejs10.x

Resources:
  AccountsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "accounts"
      CodeUri: accounts/
      Events:
        Accounts:
          Type: Api
          Properties:
            Path: /accounts
            Method: get
        VerifyPIN:
          Type: Api
          Properties:
            Path: /accounts/verifyPIN
            Method: post
      Environment:
        Variables:
          TABLE_NAME: !Ref AccountsTable
      Policies: AmazonDynamoDBFullAccess

  AccountsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: accounts
      AttributeDefinitions:
        - AttributeName: accountNo
          AttributeType: S
        - AttributeName: cardNo
          AttributeType: S
      KeySchema:
        - AttributeName: accountNo
          KeyType: HASH
        - AttributeName: cardNo
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  # InitFunction:
  #   Type: AWS::Lambda::Function
  #   Policies: AWSLambdaDynamoDBExecutionRole
  #   Properties:
  #     Code:
  #       ZipFile: >
  #         const AWS = require("aws-sdk");
  #         const response = require("cfn-response");
  #         const docClient = new AWS.DynamoDB.DocumentClient();
  #         exports.handler = function(event, context) {
  #             console.log(JSON.stringify(event,null,2));
  #             var params = {
  #               TableName: event.ResourceProperties.DynamoTableName,
  #               Item:{
  #                   "id": "abc123"
  #               }
  #           };
  #         docClient.put(params, function(err, data) { if (err) {
  #           response.send(event, context, "FAILED", {});
  #         } else {
  #           response.send(event, context, "SUCCESS", {});
  #         }
  #         });
  #         };
  #Policies: AmazonDynamoDBFullAccess # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
# More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api

# Outputs:
#   # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
#   # Find out more about other implicit resources you can reference within SAM
#   # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
#   CoinifyApi:
#     Description: "API Gateway endpoint URL for Prod stage for Coinify App."
#     Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
#   CustomersFunction:
#     Description: "Hello World Lambda Function ARN"
#     Value: !GetAtt CustomersFunction.Arn
#   CustomersFunctionIamRole:
#     Description: "Implicit IAM Role created for Hello World function"
#     Value: !GetAtt CustomersFunctionIamRole.Arn
